// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: personRpc.proto

package cn.com.code4fun.proto.service;

/**
 * <pre>
 * 定义出参
 * </pre>
 *
 * Protobuf type {@code cn.com.code4fun.proto.service.PersonResponse}
 */
public final class PersonResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:cn.com.code4fun.proto.service.PersonResponse)
    PersonResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PersonResponse.newBuilder() to construct.
  private PersonResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PersonResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PersonResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cn.com.code4fun.proto.service.PersonRpcService.internal_static_cn_com_code4fun_proto_service_PersonResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cn.com.code4fun.proto.service.PersonRpcService.internal_static_cn_com_code4fun_proto_service_PersonResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cn.com.code4fun.proto.service.PersonResponse.class, cn.com.code4fun.proto.service.PersonResponse.Builder.class);
  }

  public static final int PERSON_DTO_FIELD_NUMBER = 1;
  private cn.com.code4fun.proto.dto.Person.PersonDto personDto_;
  /**
   * <code>.cn.com.code4fun.proto.dto.PersonDto person_dto = 1;</code>
   * @return Whether the personDto field is set.
   */
  @java.lang.Override
  public boolean hasPersonDto() {
    return personDto_ != null;
  }
  /**
   * <code>.cn.com.code4fun.proto.dto.PersonDto person_dto = 1;</code>
   * @return The personDto.
   */
  @java.lang.Override
  public cn.com.code4fun.proto.dto.Person.PersonDto getPersonDto() {
    return personDto_ == null ? cn.com.code4fun.proto.dto.Person.PersonDto.getDefaultInstance() : personDto_;
  }
  /**
   * <code>.cn.com.code4fun.proto.dto.PersonDto person_dto = 1;</code>
   */
  @java.lang.Override
  public cn.com.code4fun.proto.dto.Person.PersonDtoOrBuilder getPersonDtoOrBuilder() {
    return getPersonDto();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (personDto_ != null) {
      output.writeMessage(1, getPersonDto());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (personDto_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPersonDto());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cn.com.code4fun.proto.service.PersonResponse)) {
      return super.equals(obj);
    }
    cn.com.code4fun.proto.service.PersonResponse other = (cn.com.code4fun.proto.service.PersonResponse) obj;

    if (hasPersonDto() != other.hasPersonDto()) return false;
    if (hasPersonDto()) {
      if (!getPersonDto()
          .equals(other.getPersonDto())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPersonDto()) {
      hash = (37 * hash) + PERSON_DTO_FIELD_NUMBER;
      hash = (53 * hash) + getPersonDto().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.com.code4fun.proto.service.PersonResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.com.code4fun.proto.service.PersonResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.com.code4fun.proto.service.PersonResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.com.code4fun.proto.service.PersonResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.com.code4fun.proto.service.PersonResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.com.code4fun.proto.service.PersonResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.com.code4fun.proto.service.PersonResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.com.code4fun.proto.service.PersonResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.com.code4fun.proto.service.PersonResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cn.com.code4fun.proto.service.PersonResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.com.code4fun.proto.service.PersonResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.com.code4fun.proto.service.PersonResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cn.com.code4fun.proto.service.PersonResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 定义出参
   * </pre>
   *
   * Protobuf type {@code cn.com.code4fun.proto.service.PersonResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:cn.com.code4fun.proto.service.PersonResponse)
      cn.com.code4fun.proto.service.PersonResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.com.code4fun.proto.service.PersonRpcService.internal_static_cn_com_code4fun_proto_service_PersonResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.com.code4fun.proto.service.PersonRpcService.internal_static_cn_com_code4fun_proto_service_PersonResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.com.code4fun.proto.service.PersonResponse.class, cn.com.code4fun.proto.service.PersonResponse.Builder.class);
    }

    // Construct using cn.com.code4fun.proto.service.PersonResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (personDtoBuilder_ == null) {
        personDto_ = null;
      } else {
        personDto_ = null;
        personDtoBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cn.com.code4fun.proto.service.PersonRpcService.internal_static_cn_com_code4fun_proto_service_PersonResponse_descriptor;
    }

    @java.lang.Override
    public cn.com.code4fun.proto.service.PersonResponse getDefaultInstanceForType() {
      return cn.com.code4fun.proto.service.PersonResponse.getDefaultInstance();
    }

    @java.lang.Override
    public cn.com.code4fun.proto.service.PersonResponse build() {
      cn.com.code4fun.proto.service.PersonResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cn.com.code4fun.proto.service.PersonResponse buildPartial() {
      cn.com.code4fun.proto.service.PersonResponse result = new cn.com.code4fun.proto.service.PersonResponse(this);
      if (personDtoBuilder_ == null) {
        result.personDto_ = personDto_;
      } else {
        result.personDto_ = personDtoBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.com.code4fun.proto.service.PersonResponse) {
        return mergeFrom((cn.com.code4fun.proto.service.PersonResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.com.code4fun.proto.service.PersonResponse other) {
      if (other == cn.com.code4fun.proto.service.PersonResponse.getDefaultInstance()) return this;
      if (other.hasPersonDto()) {
        mergePersonDto(other.getPersonDto());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getPersonDtoFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private cn.com.code4fun.proto.dto.Person.PersonDto personDto_;
    private com.google.protobuf.SingleFieldBuilderV3<
        cn.com.code4fun.proto.dto.Person.PersonDto, cn.com.code4fun.proto.dto.Person.PersonDto.Builder, cn.com.code4fun.proto.dto.Person.PersonDtoOrBuilder> personDtoBuilder_;
    /**
     * <code>.cn.com.code4fun.proto.dto.PersonDto person_dto = 1;</code>
     * @return Whether the personDto field is set.
     */
    public boolean hasPersonDto() {
      return personDtoBuilder_ != null || personDto_ != null;
    }
    /**
     * <code>.cn.com.code4fun.proto.dto.PersonDto person_dto = 1;</code>
     * @return The personDto.
     */
    public cn.com.code4fun.proto.dto.Person.PersonDto getPersonDto() {
      if (personDtoBuilder_ == null) {
        return personDto_ == null ? cn.com.code4fun.proto.dto.Person.PersonDto.getDefaultInstance() : personDto_;
      } else {
        return personDtoBuilder_.getMessage();
      }
    }
    /**
     * <code>.cn.com.code4fun.proto.dto.PersonDto person_dto = 1;</code>
     */
    public Builder setPersonDto(cn.com.code4fun.proto.dto.Person.PersonDto value) {
      if (personDtoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        personDto_ = value;
        onChanged();
      } else {
        personDtoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.cn.com.code4fun.proto.dto.PersonDto person_dto = 1;</code>
     */
    public Builder setPersonDto(
        cn.com.code4fun.proto.dto.Person.PersonDto.Builder builderForValue) {
      if (personDtoBuilder_ == null) {
        personDto_ = builderForValue.build();
        onChanged();
      } else {
        personDtoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.cn.com.code4fun.proto.dto.PersonDto person_dto = 1;</code>
     */
    public Builder mergePersonDto(cn.com.code4fun.proto.dto.Person.PersonDto value) {
      if (personDtoBuilder_ == null) {
        if (personDto_ != null) {
          personDto_ =
            cn.com.code4fun.proto.dto.Person.PersonDto.newBuilder(personDto_).mergeFrom(value).buildPartial();
        } else {
          personDto_ = value;
        }
        onChanged();
      } else {
        personDtoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.cn.com.code4fun.proto.dto.PersonDto person_dto = 1;</code>
     */
    public Builder clearPersonDto() {
      if (personDtoBuilder_ == null) {
        personDto_ = null;
        onChanged();
      } else {
        personDto_ = null;
        personDtoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.cn.com.code4fun.proto.dto.PersonDto person_dto = 1;</code>
     */
    public cn.com.code4fun.proto.dto.Person.PersonDto.Builder getPersonDtoBuilder() {
      
      onChanged();
      return getPersonDtoFieldBuilder().getBuilder();
    }
    /**
     * <code>.cn.com.code4fun.proto.dto.PersonDto person_dto = 1;</code>
     */
    public cn.com.code4fun.proto.dto.Person.PersonDtoOrBuilder getPersonDtoOrBuilder() {
      if (personDtoBuilder_ != null) {
        return personDtoBuilder_.getMessageOrBuilder();
      } else {
        return personDto_ == null ?
            cn.com.code4fun.proto.dto.Person.PersonDto.getDefaultInstance() : personDto_;
      }
    }
    /**
     * <code>.cn.com.code4fun.proto.dto.PersonDto person_dto = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        cn.com.code4fun.proto.dto.Person.PersonDto, cn.com.code4fun.proto.dto.Person.PersonDto.Builder, cn.com.code4fun.proto.dto.Person.PersonDtoOrBuilder> 
        getPersonDtoFieldBuilder() {
      if (personDtoBuilder_ == null) {
        personDtoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            cn.com.code4fun.proto.dto.Person.PersonDto, cn.com.code4fun.proto.dto.Person.PersonDto.Builder, cn.com.code4fun.proto.dto.Person.PersonDtoOrBuilder>(
                getPersonDto(),
                getParentForChildren(),
                isClean());
        personDto_ = null;
      }
      return personDtoBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:cn.com.code4fun.proto.service.PersonResponse)
  }

  // @@protoc_insertion_point(class_scope:cn.com.code4fun.proto.service.PersonResponse)
  private static final cn.com.code4fun.proto.service.PersonResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cn.com.code4fun.proto.service.PersonResponse();
  }

  public static cn.com.code4fun.proto.service.PersonResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PersonResponse>
      PARSER = new com.google.protobuf.AbstractParser<PersonResponse>() {
    @java.lang.Override
    public PersonResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PersonResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PersonResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cn.com.code4fun.proto.service.PersonResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

