// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: personRpc.proto

package cn.com.code4fun.proto.service;

public interface PersonResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.com.code4fun.proto.service.PersonResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.cn.com.code4fun.proto.dto.PersonDto person_dto = 1;</code>
   * @return Whether the personDto field is set.
   */
  boolean hasPersonDto();
  /**
   * <code>.cn.com.code4fun.proto.dto.PersonDto person_dto = 1;</code>
   * @return The personDto.
   */
  cn.com.code4fun.proto.dto.Person.PersonDto getPersonDto();
  /**
   * <code>.cn.com.code4fun.proto.dto.PersonDto person_dto = 1;</code>
   */
  cn.com.code4fun.proto.dto.Person.PersonDtoOrBuilder getPersonDtoOrBuilder();
}
