// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: personRpc.proto

package cn.com.code4fun.proto.service;

public interface QueryPersonByUsernameRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.com.code4fun.proto.service.QueryPersonByUsernameRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
