// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package cn.com.code4fun.proto.dto;

public final class Person {
  private Person() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PersonDtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.com.code4fun.proto.dto.PersonDto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string email = 3;</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 3;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>.cn.com.code4fun.proto.dto.PersonDto.Sex sex = 4;</code>
     * @return The enum numeric value on the wire for sex.
     */
    int getSexValue();
    /**
     * <code>.cn.com.code4fun.proto.dto.PersonDto.Sex sex = 4;</code>
     * @return The sex.
     */
    cn.com.code4fun.proto.dto.Person.PersonDto.Sex getSex();

    /**
     * <code>repeated .cn.com.code4fun.proto.dto.PersonDto.PhoneNumber phone_numbers = 5;</code>
     */
    java.util.List<cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber> 
        getPhoneNumbersList();
    /**
     * <code>repeated .cn.com.code4fun.proto.dto.PersonDto.PhoneNumber phone_numbers = 5;</code>
     */
    cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber getPhoneNumbers(int index);
    /**
     * <code>repeated .cn.com.code4fun.proto.dto.PersonDto.PhoneNumber phone_numbers = 5;</code>
     */
    int getPhoneNumbersCount();
    /**
     * <code>repeated .cn.com.code4fun.proto.dto.PersonDto.PhoneNumber phone_numbers = 5;</code>
     */
    java.util.List<? extends cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumberOrBuilder> 
        getPhoneNumbersOrBuilderList();
    /**
     * <code>repeated .cn.com.code4fun.proto.dto.PersonDto.PhoneNumber phone_numbers = 5;</code>
     */
    cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumberOrBuilder getPhoneNumbersOrBuilder(
        int index);

    /**
     * <code>map&lt;string, string&gt; tags = 6;</code>
     */
    int getTagsCount();
    /**
     * <code>map&lt;string, string&gt; tags = 6;</code>
     */
    boolean containsTags(
        java.lang.String key);
    /**
     * Use {@link #getTagsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getTags();
    /**
     * <code>map&lt;string, string&gt; tags = 6;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getTagsMap();
    /**
     * <code>map&lt;string, string&gt; tags = 6;</code>
     */

    /* nullable */
java.lang.String getTagsOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; tags = 6;</code>
     */

    java.lang.String getTagsOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code cn.com.code4fun.proto.dto.PersonDto}
   */
  public static final class PersonDto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.com.code4fun.proto.dto.PersonDto)
      PersonDtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PersonDto.newBuilder() to construct.
    private PersonDto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PersonDto() {
      name_ = "";
      email_ = "";
      sex_ = 0;
      phoneNumbers_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PersonDto();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.com.code4fun.proto.dto.Person.internal_static_cn_com_code4fun_proto_dto_PersonDto_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetTags();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.com.code4fun.proto.dto.Person.internal_static_cn_com_code4fun_proto_dto_PersonDto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.com.code4fun.proto.dto.Person.PersonDto.class, cn.com.code4fun.proto.dto.Person.PersonDto.Builder.class);
    }

    /**
     * Protobuf enum {@code cn.com.code4fun.proto.dto.PersonDto.Sex}
     */
    public enum Sex
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>DEFAULT = 0;</code>
       */
      DEFAULT(0),
      /**
       * <code>Male = 1;</code>
       */
      Male(1),
      /**
       * <code>Female = 2;</code>
       */
      Female(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>DEFAULT = 0;</code>
       */
      public static final int DEFAULT_VALUE = 0;
      /**
       * <code>Male = 1;</code>
       */
      public static final int Male_VALUE = 1;
      /**
       * <code>Female = 2;</code>
       */
      public static final int Female_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Sex valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Sex forNumber(int value) {
        switch (value) {
          case 0: return DEFAULT;
          case 1: return Male;
          case 2: return Female;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Sex>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Sex> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Sex>() {
              public Sex findValueByNumber(int number) {
                return Sex.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return cn.com.code4fun.proto.dto.Person.PersonDto.getDescriptor().getEnumTypes().get(0);
      }

      private static final Sex[] VALUES = values();

      public static Sex valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Sex(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:cn.com.code4fun.proto.dto.PersonDto.Sex)
    }

    public interface PhoneNumberOrBuilder extends
        // @@protoc_insertion_point(interface_extends:cn.com.code4fun.proto.dto.PersonDto.PhoneNumber)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string number = 1;</code>
       * @return The number.
       */
      java.lang.String getNumber();
      /**
       * <code>string number = 1;</code>
       * @return The bytes for number.
       */
      com.google.protobuf.ByteString
          getNumberBytes();

      /**
       * <code>.cn.com.code4fun.proto.dto.PersonDto.PhoneNumber.PhoneType phone_type = 2;</code>
       * @return The enum numeric value on the wire for phoneType.
       */
      int getPhoneTypeValue();
      /**
       * <code>.cn.com.code4fun.proto.dto.PersonDto.PhoneNumber.PhoneType phone_type = 2;</code>
       * @return The phoneType.
       */
      cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber.PhoneType getPhoneType();
    }
    /**
     * Protobuf type {@code cn.com.code4fun.proto.dto.PersonDto.PhoneNumber}
     */
    public static final class PhoneNumber extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:cn.com.code4fun.proto.dto.PersonDto.PhoneNumber)
        PhoneNumberOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use PhoneNumber.newBuilder() to construct.
      private PhoneNumber(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private PhoneNumber() {
        number_ = "";
        phoneType_ = 0;
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new PhoneNumber();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.com.code4fun.proto.dto.Person.internal_static_cn_com_code4fun_proto_dto_PersonDto_PhoneNumber_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.com.code4fun.proto.dto.Person.internal_static_cn_com_code4fun_proto_dto_PersonDto_PhoneNumber_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber.class, cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber.Builder.class);
      }

      /**
       * Protobuf enum {@code cn.com.code4fun.proto.dto.PersonDto.PhoneNumber.PhoneType}
       */
      public enum PhoneType
          implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>Mobile = 0;</code>
         */
        Mobile(0),
        /**
         * <code>Home = 1;</code>
         */
        Home(1),
        /**
         * <code>Work = 2;</code>
         */
        Work(2),
        UNRECOGNIZED(-1),
        ;

        /**
         * <code>Mobile = 0;</code>
         */
        public static final int Mobile_VALUE = 0;
        /**
         * <code>Home = 1;</code>
         */
        public static final int Home_VALUE = 1;
        /**
         * <code>Work = 2;</code>
         */
        public static final int Work_VALUE = 2;


        public final int getNumber() {
          if (this == UNRECOGNIZED) {
            throw new java.lang.IllegalArgumentException(
                "Can't get the number of an unknown enum value.");
          }
          return value;
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static PhoneType valueOf(int value) {
          return forNumber(value);
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         */
        public static PhoneType forNumber(int value) {
          switch (value) {
            case 0: return Mobile;
            case 1: return Home;
            case 2: return Work;
            default: return null;
          }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
            internalGetValueMap() {
          return internalValueMap;
        }
        private static final com.google.protobuf.Internal.EnumLiteMap<
            PhoneType> internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
                public PhoneType findValueByNumber(int number) {
                  return PhoneType.forNumber(number);
                }
              };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
          if (this == UNRECOGNIZED) {
            throw new java.lang.IllegalStateException(
                "Can't get the descriptor of an unrecognized enum value.");
          }
          return getDescriptor().getValues().get(ordinal());
        }
        public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
          return cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber.getDescriptor().getEnumTypes().get(0);
        }

        private static final PhoneType[] VALUES = values();

        public static PhoneType valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
          if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "EnumValueDescriptor is not for this type.");
          }
          if (desc.getIndex() == -1) {
            return UNRECOGNIZED;
          }
          return VALUES[desc.getIndex()];
        }

        private final int value;

        private PhoneType(int value) {
          this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:cn.com.code4fun.proto.dto.PersonDto.PhoneNumber.PhoneType)
      }

      public static final int NUMBER_FIELD_NUMBER = 1;
      private volatile java.lang.Object number_;
      /**
       * <code>string number = 1;</code>
       * @return The number.
       */
      @java.lang.Override
      public java.lang.String getNumber() {
        java.lang.Object ref = number_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          number_ = s;
          return s;
        }
      }
      /**
       * <code>string number = 1;</code>
       * @return The bytes for number.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getNumberBytes() {
        java.lang.Object ref = number_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          number_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int PHONE_TYPE_FIELD_NUMBER = 2;
      private int phoneType_;
      /**
       * <code>.cn.com.code4fun.proto.dto.PersonDto.PhoneNumber.PhoneType phone_type = 2;</code>
       * @return The enum numeric value on the wire for phoneType.
       */
      @java.lang.Override public int getPhoneTypeValue() {
        return phoneType_;
      }
      /**
       * <code>.cn.com.code4fun.proto.dto.PersonDto.PhoneNumber.PhoneType phone_type = 2;</code>
       * @return The phoneType.
       */
      @java.lang.Override public cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber.PhoneType getPhoneType() {
        @SuppressWarnings("deprecation")
        cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber.PhoneType result = cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber.PhoneType.valueOf(phoneType_);
        return result == null ? cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber.PhoneType.UNRECOGNIZED : result;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(number_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, number_);
        }
        if (phoneType_ != cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber.PhoneType.Mobile.getNumber()) {
          output.writeEnum(2, phoneType_);
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(number_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, number_);
        }
        if (phoneType_ != cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber.PhoneType.Mobile.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(2, phoneType_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber)) {
          return super.equals(obj);
        }
        cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber other = (cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber) obj;

        if (!getNumber()
            .equals(other.getNumber())) return false;
        if (phoneType_ != other.phoneType_) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + NUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getNumber().hashCode();
        hash = (37 * hash) + PHONE_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + phoneType_;
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code cn.com.code4fun.proto.dto.PersonDto.PhoneNumber}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:cn.com.code4fun.proto.dto.PersonDto.PhoneNumber)
          cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumberOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return cn.com.code4fun.proto.dto.Person.internal_static_cn_com_code4fun_proto_dto_PersonDto_PhoneNumber_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return cn.com.code4fun.proto.dto.Person.internal_static_cn_com_code4fun_proto_dto_PersonDto_PhoneNumber_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber.class, cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber.Builder.class);
        }

        // Construct using cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          number_ = "";

          phoneType_ = 0;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return cn.com.code4fun.proto.dto.Person.internal_static_cn_com_code4fun_proto_dto_PersonDto_PhoneNumber_descriptor;
        }

        @java.lang.Override
        public cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber getDefaultInstanceForType() {
          return cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber.getDefaultInstance();
        }

        @java.lang.Override
        public cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber build() {
          cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber buildPartial() {
          cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber result = new cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber(this);
          result.number_ = number_;
          result.phoneType_ = phoneType_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber) {
            return mergeFrom((cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber other) {
          if (other == cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber.getDefaultInstance()) return this;
          if (!other.getNumber().isEmpty()) {
            number_ = other.number_;
            onChanged();
          }
          if (other.phoneType_ != 0) {
            setPhoneTypeValue(other.getPhoneTypeValue());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  number_ = input.readStringRequireUtf8();

                  break;
                } // case 10
                case 16: {
                  phoneType_ = input.readEnum();

                  break;
                } // case 16
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }

        private java.lang.Object number_ = "";
        /**
         * <code>string number = 1;</code>
         * @return The number.
         */
        public java.lang.String getNumber() {
          java.lang.Object ref = number_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            number_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string number = 1;</code>
         * @return The bytes for number.
         */
        public com.google.protobuf.ByteString
            getNumberBytes() {
          java.lang.Object ref = number_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            number_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string number = 1;</code>
         * @param value The number to set.
         * @return This builder for chaining.
         */
        public Builder setNumber(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          number_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string number = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearNumber() {
          
          number_ = getDefaultInstance().getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>string number = 1;</code>
         * @param value The bytes for number to set.
         * @return This builder for chaining.
         */
        public Builder setNumberBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          number_ = value;
          onChanged();
          return this;
        }

        private int phoneType_ = 0;
        /**
         * <code>.cn.com.code4fun.proto.dto.PersonDto.PhoneNumber.PhoneType phone_type = 2;</code>
         * @return The enum numeric value on the wire for phoneType.
         */
        @java.lang.Override public int getPhoneTypeValue() {
          return phoneType_;
        }
        /**
         * <code>.cn.com.code4fun.proto.dto.PersonDto.PhoneNumber.PhoneType phone_type = 2;</code>
         * @param value The enum numeric value on the wire for phoneType to set.
         * @return This builder for chaining.
         */
        public Builder setPhoneTypeValue(int value) {
          
          phoneType_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>.cn.com.code4fun.proto.dto.PersonDto.PhoneNumber.PhoneType phone_type = 2;</code>
         * @return The phoneType.
         */
        @java.lang.Override
        public cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber.PhoneType getPhoneType() {
          @SuppressWarnings("deprecation")
          cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber.PhoneType result = cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber.PhoneType.valueOf(phoneType_);
          return result == null ? cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber.PhoneType.UNRECOGNIZED : result;
        }
        /**
         * <code>.cn.com.code4fun.proto.dto.PersonDto.PhoneNumber.PhoneType phone_type = 2;</code>
         * @param value The phoneType to set.
         * @return This builder for chaining.
         */
        public Builder setPhoneType(cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber.PhoneType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          
          phoneType_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>.cn.com.code4fun.proto.dto.PersonDto.PhoneNumber.PhoneType phone_type = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearPhoneType() {
          
          phoneType_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:cn.com.code4fun.proto.dto.PersonDto.PhoneNumber)
      }

      // @@protoc_insertion_point(class_scope:cn.com.code4fun.proto.dto.PersonDto.PhoneNumber)
      private static final cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber();
      }

      public static cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<PhoneNumber>
          PARSER = new com.google.protobuf.AbstractParser<PhoneNumber>() {
        @java.lang.Override
        public PhoneNumber parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<PhoneNumber> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<PhoneNumber> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    private volatile java.lang.Object email_;
    /**
     * <code>string email = 3;</code>
     * @return The email.
     */
    @java.lang.Override
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 3;</code>
     * @return The bytes for email.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEX_FIELD_NUMBER = 4;
    private int sex_;
    /**
     * <code>.cn.com.code4fun.proto.dto.PersonDto.Sex sex = 4;</code>
     * @return The enum numeric value on the wire for sex.
     */
    @java.lang.Override public int getSexValue() {
      return sex_;
    }
    /**
     * <code>.cn.com.code4fun.proto.dto.PersonDto.Sex sex = 4;</code>
     * @return The sex.
     */
    @java.lang.Override public cn.com.code4fun.proto.dto.Person.PersonDto.Sex getSex() {
      @SuppressWarnings("deprecation")
      cn.com.code4fun.proto.dto.Person.PersonDto.Sex result = cn.com.code4fun.proto.dto.Person.PersonDto.Sex.valueOf(sex_);
      return result == null ? cn.com.code4fun.proto.dto.Person.PersonDto.Sex.UNRECOGNIZED : result;
    }

    public static final int PHONE_NUMBERS_FIELD_NUMBER = 5;
    private java.util.List<cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber> phoneNumbers_;
    /**
     * <code>repeated .cn.com.code4fun.proto.dto.PersonDto.PhoneNumber phone_numbers = 5;</code>
     */
    @java.lang.Override
    public java.util.List<cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber> getPhoneNumbersList() {
      return phoneNumbers_;
    }
    /**
     * <code>repeated .cn.com.code4fun.proto.dto.PersonDto.PhoneNumber phone_numbers = 5;</code>
     */
    @java.lang.Override
    public java.util.List<? extends cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumberOrBuilder> 
        getPhoneNumbersOrBuilderList() {
      return phoneNumbers_;
    }
    /**
     * <code>repeated .cn.com.code4fun.proto.dto.PersonDto.PhoneNumber phone_numbers = 5;</code>
     */
    @java.lang.Override
    public int getPhoneNumbersCount() {
      return phoneNumbers_.size();
    }
    /**
     * <code>repeated .cn.com.code4fun.proto.dto.PersonDto.PhoneNumber phone_numbers = 5;</code>
     */
    @java.lang.Override
    public cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber getPhoneNumbers(int index) {
      return phoneNumbers_.get(index);
    }
    /**
     * <code>repeated .cn.com.code4fun.proto.dto.PersonDto.PhoneNumber phone_numbers = 5;</code>
     */
    @java.lang.Override
    public cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumberOrBuilder getPhoneNumbersOrBuilder(
        int index) {
      return phoneNumbers_.get(index);
    }

    public static final int TAGS_FIELD_NUMBER = 6;
    private static final class TagsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  cn.com.code4fun.proto.dto.Person.internal_static_cn_com_code4fun_proto_dto_PersonDto_TagsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> tags_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetTags() {
      if (tags_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            TagsDefaultEntryHolder.defaultEntry);
      }
      return tags_;
    }

    public int getTagsCount() {
      return internalGetTags().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; tags = 6;</code>
     */

    @java.lang.Override
    public boolean containsTags(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetTags().getMap().containsKey(key);
    }
    /**
     * Use {@link #getTagsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getTags() {
      return getTagsMap();
    }
    /**
     * <code>map&lt;string, string&gt; tags = 6;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getTagsMap() {
      return internalGetTags().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; tags = 6;</code>
     */
    @java.lang.Override

    public java.lang.String getTagsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetTags().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; tags = 6;</code>
     */
    @java.lang.Override

    public java.lang.String getTagsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetTags().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
      }
      if (sex_ != cn.com.code4fun.proto.dto.Person.PersonDto.Sex.DEFAULT.getNumber()) {
        output.writeEnum(4, sex_);
      }
      for (int i = 0; i < phoneNumbers_.size(); i++) {
        output.writeMessage(5, phoneNumbers_.get(i));
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetTags(),
          TagsDefaultEntryHolder.defaultEntry,
          6);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
      }
      if (sex_ != cn.com.code4fun.proto.dto.Person.PersonDto.Sex.DEFAULT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, sex_);
      }
      for (int i = 0; i < phoneNumbers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, phoneNumbers_.get(i));
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetTags().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        tags__ = TagsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(6, tags__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.com.code4fun.proto.dto.Person.PersonDto)) {
        return super.equals(obj);
      }
      cn.com.code4fun.proto.dto.Person.PersonDto other = (cn.com.code4fun.proto.dto.Person.PersonDto) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getEmail()
          .equals(other.getEmail())) return false;
      if (sex_ != other.sex_) return false;
      if (!getPhoneNumbersList()
          .equals(other.getPhoneNumbersList())) return false;
      if (!internalGetTags().equals(
          other.internalGetTags())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (37 * hash) + SEX_FIELD_NUMBER;
      hash = (53 * hash) + sex_;
      if (getPhoneNumbersCount() > 0) {
        hash = (37 * hash) + PHONE_NUMBERS_FIELD_NUMBER;
        hash = (53 * hash) + getPhoneNumbersList().hashCode();
      }
      if (!internalGetTags().getMap().isEmpty()) {
        hash = (37 * hash) + TAGS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetTags().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.com.code4fun.proto.dto.Person.PersonDto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.com.code4fun.proto.dto.Person.PersonDto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.com.code4fun.proto.dto.Person.PersonDto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.com.code4fun.proto.dto.Person.PersonDto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.com.code4fun.proto.dto.Person.PersonDto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.com.code4fun.proto.dto.Person.PersonDto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.com.code4fun.proto.dto.Person.PersonDto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.com.code4fun.proto.dto.Person.PersonDto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.com.code4fun.proto.dto.Person.PersonDto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.com.code4fun.proto.dto.Person.PersonDto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.com.code4fun.proto.dto.Person.PersonDto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.com.code4fun.proto.dto.Person.PersonDto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.com.code4fun.proto.dto.Person.PersonDto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.com.code4fun.proto.dto.PersonDto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.com.code4fun.proto.dto.PersonDto)
        cn.com.code4fun.proto.dto.Person.PersonDtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.com.code4fun.proto.dto.Person.internal_static_cn_com_code4fun_proto_dto_PersonDto_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetTags();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetMutableTags();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.com.code4fun.proto.dto.Person.internal_static_cn_com_code4fun_proto_dto_PersonDto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.com.code4fun.proto.dto.Person.PersonDto.class, cn.com.code4fun.proto.dto.Person.PersonDto.Builder.class);
      }

      // Construct using cn.com.code4fun.proto.dto.Person.PersonDto.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        email_ = "";

        sex_ = 0;

        if (phoneNumbersBuilder_ == null) {
          phoneNumbers_ = java.util.Collections.emptyList();
        } else {
          phoneNumbers_ = null;
          phoneNumbersBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        internalGetMutableTags().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.com.code4fun.proto.dto.Person.internal_static_cn_com_code4fun_proto_dto_PersonDto_descriptor;
      }

      @java.lang.Override
      public cn.com.code4fun.proto.dto.Person.PersonDto getDefaultInstanceForType() {
        return cn.com.code4fun.proto.dto.Person.PersonDto.getDefaultInstance();
      }

      @java.lang.Override
      public cn.com.code4fun.proto.dto.Person.PersonDto build() {
        cn.com.code4fun.proto.dto.Person.PersonDto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.com.code4fun.proto.dto.Person.PersonDto buildPartial() {
        cn.com.code4fun.proto.dto.Person.PersonDto result = new cn.com.code4fun.proto.dto.Person.PersonDto(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.name_ = name_;
        result.email_ = email_;
        result.sex_ = sex_;
        if (phoneNumbersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            phoneNumbers_ = java.util.Collections.unmodifiableList(phoneNumbers_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.phoneNumbers_ = phoneNumbers_;
        } else {
          result.phoneNumbers_ = phoneNumbersBuilder_.build();
        }
        result.tags_ = internalGetTags();
        result.tags_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.com.code4fun.proto.dto.Person.PersonDto) {
          return mergeFrom((cn.com.code4fun.proto.dto.Person.PersonDto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.com.code4fun.proto.dto.Person.PersonDto other) {
        if (other == cn.com.code4fun.proto.dto.Person.PersonDto.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (other.sex_ != 0) {
          setSexValue(other.getSexValue());
        }
        if (phoneNumbersBuilder_ == null) {
          if (!other.phoneNumbers_.isEmpty()) {
            if (phoneNumbers_.isEmpty()) {
              phoneNumbers_ = other.phoneNumbers_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePhoneNumbersIsMutable();
              phoneNumbers_.addAll(other.phoneNumbers_);
            }
            onChanged();
          }
        } else {
          if (!other.phoneNumbers_.isEmpty()) {
            if (phoneNumbersBuilder_.isEmpty()) {
              phoneNumbersBuilder_.dispose();
              phoneNumbersBuilder_ = null;
              phoneNumbers_ = other.phoneNumbers_;
              bitField0_ = (bitField0_ & ~0x00000001);
              phoneNumbersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPhoneNumbersFieldBuilder() : null;
            } else {
              phoneNumbersBuilder_.addAllMessages(other.phoneNumbers_);
            }
          }
        }
        internalGetMutableTags().mergeFrom(
            other.internalGetTags());
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();

                break;
              } // case 8
              case 18: {
                name_ = input.readStringRequireUtf8();

                break;
              } // case 18
              case 26: {
                email_ = input.readStringRequireUtf8();

                break;
              } // case 26
              case 32: {
                sex_ = input.readEnum();

                break;
              } // case 32
              case 42: {
                cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber m =
                    input.readMessage(
                        cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber.parser(),
                        extensionRegistry);
                if (phoneNumbersBuilder_ == null) {
                  ensurePhoneNumbersIsMutable();
                  phoneNumbers_.add(m);
                } else {
                  phoneNumbersBuilder_.addMessage(m);
                }
                break;
              } // case 42
              case 50: {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                tags__ = input.readMessage(
                    TagsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableTags().getMutableMap().put(
                    tags__.getKey(), tags__.getValue());
                break;
              } // case 50
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 3;</code>
       * @return The email.
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       * @return The bytes for email.
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private int sex_ = 0;
      /**
       * <code>.cn.com.code4fun.proto.dto.PersonDto.Sex sex = 4;</code>
       * @return The enum numeric value on the wire for sex.
       */
      @java.lang.Override public int getSexValue() {
        return sex_;
      }
      /**
       * <code>.cn.com.code4fun.proto.dto.PersonDto.Sex sex = 4;</code>
       * @param value The enum numeric value on the wire for sex to set.
       * @return This builder for chaining.
       */
      public Builder setSexValue(int value) {
        
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.cn.com.code4fun.proto.dto.PersonDto.Sex sex = 4;</code>
       * @return The sex.
       */
      @java.lang.Override
      public cn.com.code4fun.proto.dto.Person.PersonDto.Sex getSex() {
        @SuppressWarnings("deprecation")
        cn.com.code4fun.proto.dto.Person.PersonDto.Sex result = cn.com.code4fun.proto.dto.Person.PersonDto.Sex.valueOf(sex_);
        return result == null ? cn.com.code4fun.proto.dto.Person.PersonDto.Sex.UNRECOGNIZED : result;
      }
      /**
       * <code>.cn.com.code4fun.proto.dto.PersonDto.Sex sex = 4;</code>
       * @param value The sex to set.
       * @return This builder for chaining.
       */
      public Builder setSex(cn.com.code4fun.proto.dto.Person.PersonDto.Sex value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        sex_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.cn.com.code4fun.proto.dto.PersonDto.Sex sex = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSex() {
        
        sex_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber> phoneNumbers_ =
        java.util.Collections.emptyList();
      private void ensurePhoneNumbersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          phoneNumbers_ = new java.util.ArrayList<cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber>(phoneNumbers_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber, cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber.Builder, cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumberOrBuilder> phoneNumbersBuilder_;

      /**
       * <code>repeated .cn.com.code4fun.proto.dto.PersonDto.PhoneNumber phone_numbers = 5;</code>
       */
      public java.util.List<cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber> getPhoneNumbersList() {
        if (phoneNumbersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(phoneNumbers_);
        } else {
          return phoneNumbersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .cn.com.code4fun.proto.dto.PersonDto.PhoneNumber phone_numbers = 5;</code>
       */
      public int getPhoneNumbersCount() {
        if (phoneNumbersBuilder_ == null) {
          return phoneNumbers_.size();
        } else {
          return phoneNumbersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .cn.com.code4fun.proto.dto.PersonDto.PhoneNumber phone_numbers = 5;</code>
       */
      public cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber getPhoneNumbers(int index) {
        if (phoneNumbersBuilder_ == null) {
          return phoneNumbers_.get(index);
        } else {
          return phoneNumbersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .cn.com.code4fun.proto.dto.PersonDto.PhoneNumber phone_numbers = 5;</code>
       */
      public Builder setPhoneNumbers(
          int index, cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber value) {
        if (phoneNumbersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneNumbersIsMutable();
          phoneNumbers_.set(index, value);
          onChanged();
        } else {
          phoneNumbersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cn.com.code4fun.proto.dto.PersonDto.PhoneNumber phone_numbers = 5;</code>
       */
      public Builder setPhoneNumbers(
          int index, cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber.Builder builderForValue) {
        if (phoneNumbersBuilder_ == null) {
          ensurePhoneNumbersIsMutable();
          phoneNumbers_.set(index, builderForValue.build());
          onChanged();
        } else {
          phoneNumbersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cn.com.code4fun.proto.dto.PersonDto.PhoneNumber phone_numbers = 5;</code>
       */
      public Builder addPhoneNumbers(cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber value) {
        if (phoneNumbersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneNumbersIsMutable();
          phoneNumbers_.add(value);
          onChanged();
        } else {
          phoneNumbersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .cn.com.code4fun.proto.dto.PersonDto.PhoneNumber phone_numbers = 5;</code>
       */
      public Builder addPhoneNumbers(
          int index, cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber value) {
        if (phoneNumbersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhoneNumbersIsMutable();
          phoneNumbers_.add(index, value);
          onChanged();
        } else {
          phoneNumbersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cn.com.code4fun.proto.dto.PersonDto.PhoneNumber phone_numbers = 5;</code>
       */
      public Builder addPhoneNumbers(
          cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber.Builder builderForValue) {
        if (phoneNumbersBuilder_ == null) {
          ensurePhoneNumbersIsMutable();
          phoneNumbers_.add(builderForValue.build());
          onChanged();
        } else {
          phoneNumbersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cn.com.code4fun.proto.dto.PersonDto.PhoneNumber phone_numbers = 5;</code>
       */
      public Builder addPhoneNumbers(
          int index, cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber.Builder builderForValue) {
        if (phoneNumbersBuilder_ == null) {
          ensurePhoneNumbersIsMutable();
          phoneNumbers_.add(index, builderForValue.build());
          onChanged();
        } else {
          phoneNumbersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cn.com.code4fun.proto.dto.PersonDto.PhoneNumber phone_numbers = 5;</code>
       */
      public Builder addAllPhoneNumbers(
          java.lang.Iterable<? extends cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber> values) {
        if (phoneNumbersBuilder_ == null) {
          ensurePhoneNumbersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, phoneNumbers_);
          onChanged();
        } else {
          phoneNumbersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .cn.com.code4fun.proto.dto.PersonDto.PhoneNumber phone_numbers = 5;</code>
       */
      public Builder clearPhoneNumbers() {
        if (phoneNumbersBuilder_ == null) {
          phoneNumbers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          phoneNumbersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .cn.com.code4fun.proto.dto.PersonDto.PhoneNumber phone_numbers = 5;</code>
       */
      public Builder removePhoneNumbers(int index) {
        if (phoneNumbersBuilder_ == null) {
          ensurePhoneNumbersIsMutable();
          phoneNumbers_.remove(index);
          onChanged();
        } else {
          phoneNumbersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .cn.com.code4fun.proto.dto.PersonDto.PhoneNumber phone_numbers = 5;</code>
       */
      public cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber.Builder getPhoneNumbersBuilder(
          int index) {
        return getPhoneNumbersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .cn.com.code4fun.proto.dto.PersonDto.PhoneNumber phone_numbers = 5;</code>
       */
      public cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumberOrBuilder getPhoneNumbersOrBuilder(
          int index) {
        if (phoneNumbersBuilder_ == null) {
          return phoneNumbers_.get(index);  } else {
          return phoneNumbersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .cn.com.code4fun.proto.dto.PersonDto.PhoneNumber phone_numbers = 5;</code>
       */
      public java.util.List<? extends cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumberOrBuilder> 
           getPhoneNumbersOrBuilderList() {
        if (phoneNumbersBuilder_ != null) {
          return phoneNumbersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(phoneNumbers_);
        }
      }
      /**
       * <code>repeated .cn.com.code4fun.proto.dto.PersonDto.PhoneNumber phone_numbers = 5;</code>
       */
      public cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber.Builder addPhoneNumbersBuilder() {
        return getPhoneNumbersFieldBuilder().addBuilder(
            cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber.getDefaultInstance());
      }
      /**
       * <code>repeated .cn.com.code4fun.proto.dto.PersonDto.PhoneNumber phone_numbers = 5;</code>
       */
      public cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber.Builder addPhoneNumbersBuilder(
          int index) {
        return getPhoneNumbersFieldBuilder().addBuilder(
            index, cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber.getDefaultInstance());
      }
      /**
       * <code>repeated .cn.com.code4fun.proto.dto.PersonDto.PhoneNumber phone_numbers = 5;</code>
       */
      public java.util.List<cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber.Builder> 
           getPhoneNumbersBuilderList() {
        return getPhoneNumbersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber, cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber.Builder, cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumberOrBuilder> 
          getPhoneNumbersFieldBuilder() {
        if (phoneNumbersBuilder_ == null) {
          phoneNumbersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber, cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumber.Builder, cn.com.code4fun.proto.dto.Person.PersonDto.PhoneNumberOrBuilder>(
                  phoneNumbers_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          phoneNumbers_ = null;
        }
        return phoneNumbersBuilder_;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> tags_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetTags() {
        if (tags_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              TagsDefaultEntryHolder.defaultEntry);
        }
        return tags_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableTags() {
        onChanged();;
        if (tags_ == null) {
          tags_ = com.google.protobuf.MapField.newMapField(
              TagsDefaultEntryHolder.defaultEntry);
        }
        if (!tags_.isMutable()) {
          tags_ = tags_.copy();
        }
        return tags_;
      }

      public int getTagsCount() {
        return internalGetTags().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; tags = 6;</code>
       */

      @java.lang.Override
      public boolean containsTags(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetTags().getMap().containsKey(key);
      }
      /**
       * Use {@link #getTagsMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getTags() {
        return getTagsMap();
      }
      /**
       * <code>map&lt;string, string&gt; tags = 6;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, java.lang.String> getTagsMap() {
        return internalGetTags().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; tags = 6;</code>
       */
      @java.lang.Override

      public java.lang.String getTagsOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetTags().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; tags = 6;</code>
       */
      @java.lang.Override

      public java.lang.String getTagsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetTags().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearTags() {
        internalGetMutableTags().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; tags = 6;</code>
       */

      public Builder removeTags(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableTags().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableTags() {
        return internalGetMutableTags().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; tags = 6;</code>
       */
      public Builder putTags(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) {
  throw new NullPointerException("map value");
}

        internalGetMutableTags().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; tags = 6;</code>
       */

      public Builder putAllTags(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableTags().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.com.code4fun.proto.dto.PersonDto)
    }

    // @@protoc_insertion_point(class_scope:cn.com.code4fun.proto.dto.PersonDto)
    private static final cn.com.code4fun.proto.dto.Person.PersonDto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.com.code4fun.proto.dto.Person.PersonDto();
    }

    public static cn.com.code4fun.proto.dto.Person.PersonDto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PersonDto>
        PARSER = new com.google.protobuf.AbstractParser<PersonDto>() {
      @java.lang.Override
      public PersonDto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PersonDto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PersonDto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.com.code4fun.proto.dto.Person.PersonDto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_com_code4fun_proto_dto_PersonDto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_com_code4fun_proto_dto_PersonDto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_com_code4fun_proto_dto_PersonDto_TagsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_com_code4fun_proto_dto_PersonDto_TagsEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_com_code4fun_proto_dto_PersonDto_PhoneNumber_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_com_code4fun_proto_dto_PersonDto_PhoneNumber_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014person.proto\022\031cn.com.code4fun.proto.dt" +
      "o\"\346\003\n\tPersonDto\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(" +
      "\t\022\r\n\005email\030\003 \001(\t\0225\n\003sex\030\004 \001(\0162(.cn.com.c" +
      "ode4fun.proto.dto.PersonDto.Sex\022G\n\rphone" +
      "_numbers\030\005 \003(\01320.cn.com.code4fun.proto.d" +
      "to.PersonDto.PhoneNumber\022<\n\004tags\030\006 \003(\0132." +
      ".cn.com.code4fun.proto.dto.PersonDto.Tag" +
      "sEntry\032+\n\tTagsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005valu" +
      "e\030\002 \001(\t:\0028\001\032\232\001\n\013PhoneNumber\022\016\n\006number\030\001 " +
      "\001(\t\022N\n\nphone_type\030\002 \001(\0162:.cn.com.code4fu" +
      "n.proto.dto.PersonDto.PhoneNumber.PhoneT" +
      "ype\"+\n\tPhoneType\022\n\n\006Mobile\020\000\022\010\n\004Home\020\001\022\010" +
      "\n\004Work\020\002\"(\n\003Sex\022\013\n\007DEFAULT\020\000\022\010\n\004Male\020\001\022\n" +
      "\n\006Female\020\002B\033\n\031cn.com.code4fun.proto.dtob" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cn_com_code4fun_proto_dto_PersonDto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_com_code4fun_proto_dto_PersonDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_com_code4fun_proto_dto_PersonDto_descriptor,
        new java.lang.String[] { "Id", "Name", "Email", "Sex", "PhoneNumbers", "Tags", });
    internal_static_cn_com_code4fun_proto_dto_PersonDto_TagsEntry_descriptor =
      internal_static_cn_com_code4fun_proto_dto_PersonDto_descriptor.getNestedTypes().get(0);
    internal_static_cn_com_code4fun_proto_dto_PersonDto_TagsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_com_code4fun_proto_dto_PersonDto_TagsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_cn_com_code4fun_proto_dto_PersonDto_PhoneNumber_descriptor =
      internal_static_cn_com_code4fun_proto_dto_PersonDto_descriptor.getNestedTypes().get(1);
    internal_static_cn_com_code4fun_proto_dto_PersonDto_PhoneNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_com_code4fun_proto_dto_PersonDto_PhoneNumber_descriptor,
        new java.lang.String[] { "Number", "PhoneType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
